### PR TITLE
Treyhboy patch 1

### PR DESCRIPTION
**Pull request by treyhboy**
Done the specific changes requested pls review

### CODE REVIEW

**Review by ryzokuken — CHANGES_REQUESTED** [review]
Let's do it this way:

`0: <0's password>`
`x->y: <x to y's password>`

**Comment by ryzokuken** [comment]
@treyhboy Looks awesome, I see some lines start with `level` (lowercase l) and others start with `Level` (uppercase l). Fix that and we're ready to go.

Thanks.

**Comment by treyhboy** [comment]
Made it full prove now .I think we are good to go now

**Review by ryzokuken — APPROVED** [review]

**Comment by ryzokuken** [comment]
@treyhboy Looks awesome. Merging this. Thanks for your contribution.

**Pull request merged**
